name: Three.js Scene Renderer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
      - name: Install Puppeteer
        run: npm install puppeteer


      - name: Run headless browser to render scene
        run: |
          npx puppeteer \
          --no-sandbox \
          --disable-setuid-sandbox \
          --disable-dev-shm-usage \
          --disable-accelerated-2d-canvas \
          --disable-gpu \
          index.html
